services:
  - type: web
    name: agence-de-voyage-api
    env: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: agence-de-voyage-api
          property: port
    healthCheckPath: /api

